### ISSUE TITLE
compress-vpk: unhandled exception when compressing a text file

### ISSUE THREAD

**Issue by city41** [city41/ereader-tools#1]
```bash
echo "a b c" > foo.txt
compress-vpk foo.txt foo.vpk
TypeError: Cannot read properties of undefined (reading 'node')
    at write_huffman_tree (/home/matt/dotfiles/config/.config/yarn/global/node_modules/@city41/ereader-tools/dist/lib/compress.js:141:14)
    at create_huffman_tree (/home/matt/dotfiles/config/.config/yarn/global/node_modules/@city41/ereader-tools/dist/lib/compress.js:339:5)
    at compress (/home/matt/dotfiles/config/.config/yarn/global/node_modules/@city41/ereader-tools/dist/lib/compress.js:520:20)
    at main (/home/matt/dotfiles/config/.config/yarn/global/node_modules/@city41/ereader-tools/dist/cli/compress-vpk.js:48:29)
```

Which is fine, `nevpk` seg faults when trying to compress text. Compressing text is not the point of this tool.

Detect the input file is text, and emit a proper error instead of proceeding.

**Comment by city41** [comment]
Since vpk0 is a general compression routine, I think it should compress text just fine. This seems like a bug in nevpk that is now also in compress-vpk
